name: targets
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_database: ^3.0.7
  firebase_auth: 0.14.0+4
  toast: ^0.1.5
  connectivity: ^0.4.4
  firebase_core: ^0.4.0+9
  progress_dialog: ^1.1.0+1
  cloud_firestore: ^0.12.9+3
  google_maps_flutter: ^0.5.21+2
  geolocator: any
  location_permissions: ^2.0.2
  flutter_map: ^0.7.2
  http: ^0.12.0+2
  uuid: ^2.0.2
  provider: ^3.0.0+1
  geocoder: ^0.2.1
  intl_translation: ^0.17.7
  google_maps_webservice: ^0.0.14
  flutter_launcher_icons: ^0.7.3
  flutter_google_places: ^0.2.3
  flutter_spinkit: ^4.0.0
  geoflutterfire: ^2.0.3+5
  location: ^2.3.5
  rxdart: ^0.22.2
  flutter_local_notifications: ^0.8.3
  image_picker: ^0.6.1+4
  firebase_storage: ^3.0.6
  splashscreen: ^1.2.0
  flutter_custom_clippers: ^1.1.0
  firebase_messaging: ^5.1.8
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "images/logo1.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/logo1.png
  - images/background.jpg
  - assets/images/beer.png
  - assets/images/breakfast.jpeg
  - assets/images/burger.png
  - assets/images/cheeseburger.png
  - assets/images/coffee-cup.png
  - assets/images/cupcake.png
  - assets/images/lunch.jpeg
  - assets/images/pizza.png
  - assets/images/supper_1.jpeg
  - assets/images/turkey.png
  - assets/images/1.jpg
  - assets/images/2.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          style: italic
    - family: ACME
      fonts:
         - asset: assets/fonts/Acme-Regular.ttf
           weight: 400
    - family: CONCERTONE
      fonts:
         - asset: assets/fonts/ConcertOne-Regular.ttf
           weight: 400
    - family: KAUSHANSCRIPT
      fonts:
         - asset: assets/fonts/NABILA.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
